"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
type Item=Record<string,string|number|null>; type Data={guards:Item[];posts:Item[];vehicles:Item[];movements:Item[];campaign:Item|null;days:Item[];choices:Item[]};
const empty:Data={guards:[],posts:[],vehicles:[],movements:[],campaign:null,days:[],choices:[]};

export function GestaoClient({mode}:{mode:"cadastros"|"folgas"|"movimentos"}){
 const [data,setData]=useState<Data>(empty),[busy,setBusy]=useState(true),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/admin");setData(await r.json());setBusy(false)},[]);
 // The first request synchronizes this client view with the durable D1 state.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[load]);
 async function submit(e:FormEvent<HTMLFormElement>,action:string){e.preventDefault();setMessage("");const form=e.currentTarget;const body=Object.fromEntries(new FormData(form));const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,action})});const j=await r.json();setMessage(r.ok?(j.status==="waitlist"?"Limite atingido: solicitação incluída na lista de espera.":"Registro salvo com sucesso."):j.error);if(r.ok){form.reset();await load()}}
 if(busy)return <div className="module-shell"><p>Carregando dados da escala…</p></div>;
 if(mode==="cadastros")return <Module title="Cadastros operacionais" subtitle="Pessoas, postos e viaturas alimentam a mesma escala diária."><div className="forms-grid"><Form title="Novo GM" onSubmit={e=>submit(e,"guard")}><input name="registration" placeholder="Matrícula" required/><input name="name" placeholder="Nome de escala" required/><input name="platoon" placeholder="Pelotão"/><select name="baseShift"><option>12x36 dia</option><option>12x36 noite</option></select></Form><Form title="Novo posto" onSubmit={e=>submit(e,"post")}><input name="name" placeholder="Nome do posto" required/><input name="groupName" placeholder="Seção / grupo" required/><input name="sortOrder" type="number" placeholder="Ordem"/></Form><Form title="Nova viatura" onSubmit={e=>submit(e,"vehicle")}><input name="prefix" placeholder="VTR 0000" required/><select name="type"><option value="sedan">Sedan</option><option value="pickup">Caminhonete</option><option value="van">Furgão</option><option value="moto">Moto</option><option value="suv">SUV</option></select><input name="zone" placeholder="Zona de atuação"/></Form></div>{message&&<p className="notice">{message}</p>}<div className="records"><Record title="Guardas" items={data.guards} main="name" detail="registration"/><Record title="Postos" items={data.posts} main="name" detail="group_name"/><Record title="Viaturas" items={data.vehicles} main="prefix" detail="zone"/></div></Module>;
 if(mode==="movimentos")return <Module title="Movimentações do efetivo" subtitle="Afastamentos aprovados retiram o GM da escala e abrem o furo correspondente."><Form title="Novo afastamento ou ajuste" onSubmit={e=>submit(e,"movement")}><GuardSelect guards={data.guards}/><select name="type"><option value="day_off">Folga</option><option value="vacation">Férias</option><option value="course">Curso</option><option value="medical_leave">Atestado / licença</option><option value="time_bank">Banco de horas</option><option value="swap">Troca de serviço</option></select><input name="startsAt" type="datetime-local" required/><input name="endsAt" type="datetime-local" required/><input name="requestRef" placeholder="Nº do requerimento"/><input name="notes" placeholder="Observação"/></Form>{message&&<p className="notice">{message}</p>}<Record title="Registros recentes" items={data.movements} main="guard_name" detail="type"/></Module>;
 const campaign=data.campaign;return <Module title={String(campaign?.title||"Folgas mensais")} subtitle="Cada GM escolhe uma data útil e uma data de fim de semana. A capacidade é atualizada automaticamente."><div className="leave-layout"><Form title="Registrar escolha" onSubmit={e=>submit(e,"leave")}><input type="hidden" name="campaignId" value={String(campaign?.id||"")}/><GuardSelect guards={data.guards}/><select name="category"><option value="weekday">Folga durante a semana</option><option value="weekend">Folga no fim de semana</option></select><select name="date" required><option value="">Selecione uma data</option>{data.days.map(d=><option key={String(d.date)} value={String(d.date)}>{formatDate(d.date)} · {Number(d.capacity)-Number(d.used)} vagas</option>)}</select></Form><section className="capacity"><h3>Capacidade por dia</h3>{data.days.map(d=><div key={String(d.date)}><span>{formatDate(d.date)}</span><progress value={Number(d.used)} max={Number(d.capacity)}/><b>{d.used}/{d.capacity}</b></div>)}</section></div>{message&&<p className="notice">{message}</p>}<Record title="Escolhas registradas" items={data.choices} main="guard_name" detail="date"/></Module>
}
const formatDate=(value:string|number|null)=>new Date(String(value)+"T12:00:00").toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"});
function GuardSelect({guards}:{guards:Item[]}){return <select name="guardId" required><option value="">Selecione o GM</option>{guards.map(g=><option key={g.id} value={String(g.id)}>{g.name}</option>)}</select>}
function Module({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <main className="module-shell"><header><Link href="/">← Voltar à escala</Link><div><h1>{title}</h1><p>{subtitle}</p></div></header>{children}</main>}
function Form({title,onSubmit,children}:{title:string;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;children:React.ReactNode}){return <form className="data-form" onSubmit={onSubmit}><h3>{title}</h3>{children}<button className="save">Salvar</button></form>}
function Record({title,items,main,detail}:{title:string;items:Item[];main:string;detail:string}){return <section className="record-list"><h3>{title}<span>{items.length}</span></h3>{items.length===0?<p>Nenhum registro.</p>:items.map((i,n)=><div key={String(i.id??n)}><b>{String(i[main]??"")}</b><small>{String(i[detail]??"")}</small><button aria-label="Mais opções">•••</button></div>)}</section>}
