"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ModuleLoading } from "./module-loading";
import { BackToSchedule } from "./schedule-nav";
import { useScheduleDate } from "./use-schedule-date";
type Item=Record<string,string|number|null>;type Data={items:Item[];actor:{id:string;email:string;name:string}};
const entityLabels:Record<string,string>={assignment:"Escala",schedule:"Publicação",movement:"Movimentação",leave_choice:"Folga",guard:"GM",guard_import:"Importação de GMs",post:"Posto",section:"Seção",vehicle:"Viatura",vehicle_outage:"FA de viatura",weekly_slot:"Padrão semanal",pattern_slot:"Padrão 12x36",pattern_config:"Configuração 12x36",schedule_pattern:"Aplicação de padrão",notice:"Alteração diversa"};
export function HistoryDashboard(){const{date}=useScheduleDate();const[data,setData]=useState<Data|null>(null),[entity,setEntity]=useState(""),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[busyId,setBusyId]=useState<number|null>(null);const load=useCallback(async()=>{const params=new URLSearchParams({_:String(Date.now())});if(entity)params.set("entity",entity);if(query)params.set("q",query);const r=await fetch(`/api/history?${params}`,{cache:"no-store"});setData(await r.json())},[entity,query]);useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
void load()},[load]);const grouped=useMemo(()=>{const result:{label:string;items:Item[]}[]=[];for(const item of data?.items||[]){const label=new Date(String(item.created_at).replace(" ","T")+"Z").toLocaleDateString("pt-BR",{weekday:"long",day:"2-digit",month:"long"});const group=result.find(g=>g.label===label);if(group)group.items.push(item);else result.push({label,items:[item]})}return result},[data]);async function undo(item:Item){if(!confirm(`Desfazer esta alteração?\n\n${item.summary}`))return;setBusyId(Number(item.id));setMessage("");const r=await fetch("/api/history",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"undo",id:item.id})});const j=await r.json();setMessage(r.ok?j.message:j.error);setBusyId(null);if(r.ok)await load()}if(!data)return <ModuleLoading area="histórico de alterações" detail="Carregando trilha de auditoria…"/>;return <main className="history-page"><header><BackToSchedule date={date}/><div><span>RASTREABILIDADE OPERACIONAL</span><h1>Histórico de alterações</h1><p>{`Responsável atual: ${data.actor.name||data.actor.email}`}</p></div></header><section className="history-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ação ou responsável…"/><select value={entity} onChange={e=>setEntity(e.target.value)}><option value="">Todos os módulos</option>{Object.entries(entityLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button onClick={()=>void load()}>Atualizar</button></section>{message&&<p className="history-message" role="status">{message}</p>} {grouped.length===0?<p className="history-empty">Nenhuma alteração encontrada.</p>:<div className="history-groups">{grouped.map(group=><section key={group.label}><h2>{group.label}</h2>{group.items.map(item=><article className={item.undone_at?"undone":""} key={String(item.id)}><div className="history-icon">{icon(String(item.entity_type))}</div><div className="history-copy"><b>{item.summary}</b><small>{entityLabels[String(item.entity_type)]||item.entity_type} · {time(item.created_at)}</small><span>Por {item.actor_name||item.actor_email}</span>{item.undone_at&&<em>Desfeita por {item.undone_by_email} em {dateTime(item.undone_at)}</em>}<details><summary>Ver detalhes</summary><pre>{details(item)}</pre></details></div>{Number(item.undoable)===1&&!item.undone_at&&<button className="undo-button" disabled={busyId===Number(item.id)} onClick={()=>void undo(item)}>{busyId===Number(item.id)?"Desfazendo…":"↶ Desfazer"}</button>}</article>)}</section>)}</div>}</main>}
const icon=(type:string)=>type==="assignment"?"▦":type==="movement"?"⇄":type==="leave_choice"?"✓":type==="vehicle"?"▰":"✎";
const time=(value:Item[string])=>new Date(String(value).replace(" ","T")+"Z").toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"});
const dateTime=(value:Item[string])=>new Date(String(value).replace(" ","T")+"Z").toLocaleString("pt-BR");
function details(item:Item){const before=item.before_json?JSON.parse(String(item.before_json)):null,after=item.after_json?JSON.parse(String(item.after_json)):null;return JSON.stringify({antes:clean(before),depois:clean(after)},null,2)}
function clean(value:Record<string,unknown>|null){if(!value)return null;const hidden=new Set(["created_at","updated_at"]);return Object.fromEntries(Object.entries(value).filter(([key])=>!hidden.has(key)))}
