import type { Metadata } from "next";
import "./globals.css";
import "./management.css";
import "./live-schedule.css";
import "./print-schedule.css";
import "./validation.css";
import "./overtime.css";
import "./overtime-enhancements.css";
import "./drag-edit.css";
import "./patterns.css";
import "./patterns-enhanced.css";
import "./group-pattern-placement.css";
import "./pattern-resource-actions.css";
import "./extension-actions.css";
import "./usability.css";
import "./notices.css";
import "./history.css";
import "./catalog-tools.css";
import "./workforce.css";
import "./simple-ux.css";
import "./operations.css";
import "./operations-refinements.css";
import "./leave-overview.css";
import "./leave-import-refinements.css";
import "./schedule-density.css";
import "./operations-refinements.css";
import "./request-reference.css";
import "./segment-remove.css";
import "./service-adjustments.css";
import "./spreadsheet-theme.css";
import "./contextual-actions.css";
import "./monthly-planning.css";
import "./monthly-planning-simulation.css";
import "./monthly-planning-print.css";
import "./monthly-planning-priority.css";
import "./management-dashboard.css";
import "./unified-navigation.css";
import "./operational-clarity.css";
import "./interaction-system.css";
import "./app-ui.css";
import "./error-handling.css";
import { AppErrorBoundary } from "./app-error-boundary";

export const metadata: Metadata = { title:"Escala GMNH", description:"Gestão integrada de escalas da Guarda Municipal", icons:{icon:"/favicon.svg"}, openGraph:{title:"Escala GMNH",description:"Gestão integrada de efetivo",images:["/og.png"]} };
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="pt-BR"><body><AppErrorBoundary>{children}</AppErrorBoundary></body></html>}
