"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ScheduleNav, BackToSchedule } from "./schedule-nav";
import { ModuleLoading } from "./module-loading";
import { useScheduleDate } from "./use-schedule-date";
import { formatScheduleDate } from "../lib/schedule-date";
import { formatHoursDuration } from "../lib/shift-rules";

type Rec=Record<string,unknown>;
type Slot=Rec&{id:number;role:string;guard_id?:number|null;guard_name?:string|null;source_type:string};
type Vehicle=Rec&{id:number;prefix:string;type:string;zone?:string;unavailable?:number;slots?:Slot[]};
type Operation=Rec&{id:number;title:string;starts_at:string;ends_at:string;status:string;filled:number;totalSlots:number;vehicles:Vehicle[];generalSlots:Slot[]};
type Data={date:string;operations:Operation[];vehicles:Vehicle[]};
type Suggestion={guardId:number;name:string;registration:string;platoon?:string;sourceType:"available"|"redeployment"|"extension"|"overtime";originLabel?:string|null;currentHeHours:number;lastOvertime?:string|null;operationHours:number};

export function OperationsDashboard(){
  const{date}=useScheduleDate(),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[creating,setCreating]=useState(false),[busy,setBusy]=useState(false),[slotPick,setSlotPick]=useState<{operation:Operation;slot:Slot}|null>(null);
  const load=useCallback(async()=>{try{const response=await fetch(`/api/operations?date=${date}&_=${Date.now()}`,{cache:"no-store"});const value=await response.json();if(!response.ok)throw new Error(value.error);setError("");setData(value)}catch(reason){setError(reason instanceof Error?reason.message:"Não foi possível abrir as operações.")}},[date]);
  // O efeito sincroniza a data da navegação com a API de operações.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[load]);
  async function post(payload:Rec){if(busy)return null;setBusy(true);try{const response=await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const value=await response.json();setMessage(response.ok?value.message:value.error);if(response.ok&&value.operations)setData(current=>current?{...current,operations:value.operations}:current);return response.ok?value:null}finally{setBusy(false)}}
  async function create(event:FormEvent<HTMLFormElement>,vehicleIds:number[]){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const result=await post({...values,vehicleIds,date,requestedGuards:Number(values.requestedGuards)});if(result)setCreating(false)}
  if(!data&&!error)return <ModuleLoading area="operações do dia" detail={`Preparando operações de ${formatScheduleDate(date)}…`}/>;
  return <main className="operations-page"><header className="operations-top"><BackToSchedule date={date}/><div><span>MINI ESCALAS OPERACIONAIS</span><h1>Operações de {formatScheduleDate(date)}</h1><p>Viaturas, efetivo, remanejamentos e horas extras vinculados à escala do dia.</p></div><button className="primary" onClick={()=>setCreating(true)}>＋ Criar operação</button></header><ScheduleNav date={date} active="/operacoes"/>
    {message&&<p className="operations-message" role="status">{message}<button onClick={()=>setMessage("")}>×</button></p>}
    {error&&<section className="operations-empty"><b>{error}</b><button onClick={()=>void load()}>Tentar novamente</button></section>}
    {data&&<section className="operations-content"><div className="operations-summary"><span><b>{data.operations.length}</b> operações</span><span><b>{data.operations.reduce((total,item)=>total+item.vehicles.length,0)}</b> viaturas</span><span><b>{data.operations.reduce((total,item)=>total+Number(item.filled),0)}</b> GMs definidos</span></div>
      {!data.operations.length?<div className="operations-empty"><b>Nenhuma operação criada para esta data.</b><p>Crie uma mini escala sem alterar a distribuição normal até a confirmação.</p><button className="primary" onClick={()=>setCreating(true)}>＋ Criar primeira operação</button></div>:<div className="operation-list">{data.operations.map(operation=><OperationCard key={operation.id} operation={operation} busy={busy} onSlot={slot=>setSlotPick({operation,slot})} onAction={(action)=>void post({action,operationId:operation.id})}/>)}</div>}
    </section>}
    {creating&&data&&<CreateOperationDialog date={date} vehicles={data.vehicles} busy={busy} onClose={()=>setCreating(false)} onSave={create}/>}
    {slotPick&&<OperationSuggestionDialog operation={slotPick.operation} slot={slotPick.slot} busy={busy} onClose={()=>setSlotPick(null)} onAssign={async guardId=>{const result=await post({action:"assign_slot",operationId:slotPick.operation.id,slotId:slotPick.slot.id,guardId});if(result)setSlotPick(null)}} onClear={async()=>{const result=await post({action:"clear_slot",operationId:slotPick.operation.id,slotId:slotPick.slot.id});if(result)setSlotPick(null)}}/>}
  </main>
}

function OperationCard({operation,busy,onSlot,onAction}:{operation:Operation;busy:boolean;onSlot:(slot:Slot)=>void;onAction:(action:string)=>void}){
  const start=String(operation.starts_at).slice(11,16),end=String(operation.ends_at).slice(11,16),complete=Number(operation.filled)===Number(operation.totalSlots);
  return <article className="operation-card"><header><div><span className={`operation-status ${operation.status}`}>{operation.status==="confirmed"?"Confirmada":"Rascunho"}</span><h2>{operation.title}</h2><p>{start}–{end} · {String(operation.location||"Local não informado")}</p></div><div className="operation-progress"><b>{operation.filled}/{operation.totalSlots}</b><span>GMs definidos</span></div></header>
    <div className="operation-meta"><span><b>Responsável</b>{String(operation.commander||"A definir")}</span><span><b>Referência</b>{String(operation.reference||"—")}</span><span><b>Viaturas</b>{operation.vehicles.length}</span></div>
    <div className="operation-crews">{operation.vehicles.map(vehicle=><section key={vehicle.id}><header><span>{vehicleIcon(String(vehicle.type))}</span><div><b>{vehicle.prefix}</b><small>{String(vehicle.zone||"Sem área")}</small></div></header><div>{(vehicle.slots||[]).map(slot=><SlotButton key={slot.id} slot={slot} disabled={busy||operation.status==="confirmed"} onClick={()=>onSlot(slot)}/>)}</div></section>)}{operation.generalSlots.length>0&&<section className="operation-general"><header><span>GM</span><div><b>Efetivo adicional</b><small>Sem VTR vinculada</small></div></header><div>{operation.generalSlots.map(slot=><SlotButton key={slot.id} slot={slot} disabled={busy||operation.status==="confirmed"} onClick={()=>onSlot(slot)}/>)}</div></section>}</div>
    {operation.notes&&<p className="operation-notes">{String(operation.notes)}</p>}
    <footer>{operation.status==="draft"&&<><button disabled={busy} onClick={()=>onAction("cancel")}>Cancelar operação</button><button className="primary" disabled={busy||!complete} title={!complete?"Preencha todas as vagas":"Confirmar mini escala"} onClick={()=>onAction("confirm")}>Confirmar operação</button></>}</footer>
  </article>
}
function SlotButton({slot,disabled,onClick}:{slot:Slot;disabled:boolean;onClick:()=>void}){const role=slot.role==="driver"?"M":slot.role==="patrol"?"P":"GM";return <button className={`operation-slot ${slot.guard_id?"filled":"vacant"}`} disabled={disabled} onClick={onClick}><span>{role}</span><div><b>{slot.guard_name?String(slot.guard_name):"Selecionar GM"}</b><small>{slot.guard_name?sourceLabel(slot.source_type):"Vaga ainda não preenchida"}</small></div></button>}

function CreateOperationDialog({date,vehicles,busy,onClose,onSave}:{date:string;vehicles:Vehicle[];busy:boolean;onClose:()=>void;onSave:(event:FormEvent<HTMLFormElement>,vehicleIds:number[])=>void}){
  const[selected,setSelected]=useState<number[]>([]),[requested,setRequested]=useState(2),minimum=Math.max(1,selected.length*2);
  function toggle(id:number){setSelected(current=>{const next=current.includes(id)?current.filter(item=>item!==id):[...current,id];setRequested(value=>Math.max(value,next.length*2));return next})}
  return <div className="operation-dialog-backdrop"><form className="operation-dialog" onSubmit={event=>onSave(event,selected)}><header><div><small>CRIAR MINI ESCALA</small><h2>Nova operação</h2><p>Defina o período, as viaturas e o tamanho do efetivo.</p></div><button type="button" onClick={onClose}>×</button></header><div className="operation-form-grid"><label>Nome da operação<input name="title" required placeholder="Ex.: Operação Centro Seguro"/></label><label>Local / área<input name="location" placeholder="Centro, bairro, evento…"/></label><label>Início<input name="startsAt" type="datetime-local" required defaultValue={`${date}T19:00`}/></label><label>Término<input name="endsAt" type="datetime-local" required defaultValue={`${nextDate(date)}T01:00`}/></label><label>Responsável<input name="commander" placeholder="Inspetor ou encarregado"/></label><label>Ordem / referência<input name="reference" placeholder="Opcional"/></label></div><fieldset><legend>Viaturas participantes</legend><p>Viaturas em FA ficam indisponíveis. A dupla motorista/patrulheiro é criada automaticamente.</p><div className="operation-vehicle-picker">{vehicles.map(vehicle=><button type="button" key={vehicle.id} disabled={Number(vehicle.unavailable)===1} className={selected.includes(Number(vehicle.id))?"selected":""} onClick={()=>toggle(Number(vehicle.id))}><span>{vehicleIcon(String(vehicle.type))}</span><div><b>{vehicle.prefix}</b><small>{Number(vehicle.unavailable)===1?"Em FA":String(vehicle.zone||"Sem área")}</small></div><i>{selected.includes(Number(vehicle.id))?"✓":"＋"}</i></button>)}</div></fieldset><label className="operation-total">Quantidade total de GMs<input name="requestedGuards" type="number" min={minimum} value={requested} onChange={event=>setRequested(Math.max(0,Number(event.target.value)))}/><small>{minimum} vagas obrigatórias nas VTRs{requested>minimum?` + ${requested-minimum} integrante(s) adicional(is)`:""}</small></label><label>Observações<textarea name="notes" rows={3} placeholder="Apresentação, uniforme, missão ou orientação…"/></label><footer><button type="button" onClick={onClose}>Cancelar</button><button className="primary" disabled={busy||requested<minimum}>{busy?"Criando…":"Criar mini escala"}</button></footer></form></div>
}

function OperationSuggestionDialog({operation,slot,busy,onClose,onAssign,onClear}:{operation:Operation;slot:Slot;busy:boolean;onClose:()=>void;onAssign:(guardId:number)=>void;onClear:()=>void}){
 const[data,setData]=useState<{suggestions:Suggestion[]}|null>(null),[query,setQuery]=useState("");useEffect(()=>{const controller=new AbortController();fetch(`/api/operations?suggest=1&operationId=${operation.id}&slotId=${slot.id}`,{cache:"no-store",signal:controller.signal}).then(response=>response.json().then(value=>response.ok?setData(value):Promise.reject(value))).catch(()=>setData({suggestions:[]}));return()=>controller.abort()},[operation.id,slot.id]);
 const filtered=useMemo(()=>{const value=query.toLowerCase().trim();return(data?.suggestions||[]).filter(item=>!value||`${item.name} ${item.registration} ${item.platoon||""}`.toLowerCase().includes(value))},[data,query]);
 const groups=[
  {key:"available",label:"À disposição",help:"GMs avulsos, sem posto ou VTR neste período."},
  {key:"redeployment",label:"Remanejar da escala",help:"Retira o período completo da origem e marca AVISAR REMANEJAMENTO."},
  {key:"extra",label:"Extensão e hora extra",help:"Sem conflito no período, ordenado pelo menor saldo de HE."},
 ].map(group=>({...group,items:filtered.filter(item=>group.key==="extra"?["extension","overtime"].includes(item.sourceType):item.sourceType===group.key)}));
 return <div className="operation-dialog-backdrop"><section className="operation-suggest-dialog"><header><div><small>SUGESTÃO PARA A OPERAÇÃO</small><h2>{slot.role==="driver"?"Motorista":slot.role==="patrol"?"Patrulheiro":"Integrante"}</h2><p>{operation.title} · {String(operation.starts_at).slice(11,16)}–{String(operation.ends_at).slice(11,16)}</p></div><button onClick={onClose}>×</button></header>{slot.guard_name&&<div className="operation-current-guard"><span>GM ATUAL</span><b>{String(slot.guard_name)}</b><small>{sourceLabel(slot.source_type)} · ao remover, a origem do remanejamento será restaurada.</small><button disabled={busy} onClick={onClear}>Remover desta vaga</button></div>}<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar nome, matrícula ou equipe…"/><div className="operation-suggestion-list">{!data?<p>Calculando disponibilidade…</p>:filtered.length?groups.filter(group=>group.items.length).map(group=><section className={`operation-suggestion-group ${group.key}`} key={group.key}><header><div><b>{group.label}</b><small>{group.help}</small></div><span>{group.items.length}</span></header>{group.items.map(item=><button key={item.guardId} disabled={busy} onClick={()=>onAssign(item.guardId)}><span className={`source ${item.sourceType}`}>{sourceLabel(item.sourceType)}</span><div><b>{item.name}</b><small>{item.registration} · {item.platoon||"Sem equipe"}{item.originLabel?` · ${item.originLabel}`:""}</small></div><aside><b>{formatHoursDuration(item.currentHeHours)}</b><small>HE no mês</small>{item.operationHours>0&&<em>+ {formatHoursDuration(item.operationHours)} HE</em>}</aside></button>)}</section>):<p>Nenhum GM disponível sem conflito neste intervalo.</p>}</div><footer><small>Horários parcialmente sobrepostos não são remanejados automaticamente.</small><button onClick={onClose}>Fechar</button></footer></section></div>
}
const sourceLabel=(source:string)=>source==="available"?"À disposição":source==="extension"?"Extensão HE":source==="overtime"?"Hora extra":source==="redeployment"?"Remanejamento":"Pendente";
const vehicleIcon=(type:string)=>type==="moto"?"🏍":type==="pickup"?"🛻":type==="van"?"🚐":type==="suv"?"🚙":"🚓";
function nextDate(date:string){const value=new Date(`${date}T12:00:00Z`);value.setUTCDate(value.getUTCDate()+1);return value.toISOString().slice(0,10)}
