import { env } from "cloudflare:workers";
export const dynamic="force-dynamic";
const shifts=["2","3","4","1"];
function permitted(r:Request){const h=new URL(r.url).hostname;return h==="localhost"||h==="127.0.0.1"||Boolean(r.headers.get("oai-authenticated-user-id"))}
async function ensureBase(date:string){
 const guardCount=await env.DB.prepare("SELECT COUNT(*) total FROM guards").first<{total:number}>();
 if(!guardCount?.total) await env.DB.batch([
  env.DB.prepare("INSERT INTO guards (registration,name,platoon,base_shift) VALUES (?,?,?,?)").bind("1001","MARQUES","B","12x36 dia"),env.DB.prepare("INSERT INTO guards (registration,name,platoon,base_shift) VALUES (?,?,?,?)").bind("1002","ROMANA","B","12x36 dia"),env.DB.prepare("INSERT INTO guards (registration,name,platoon,base_shift) VALUES (?,?,?,?)").bind("1003","C. ALEXANDRE","B","12x36 dia"),env.DB.prepare("INSERT INTO guards (registration,name,platoon,base_shift) VALUES (?,?,?,?)").bind("1004","RIVERO","A","12x36 noite")]);
 const postCount=await env.DB.prepare("SELECT COUNT(*) total FROM posts").first<{total:number}>();
 if(!postCount?.total) await env.DB.batch([env.DB.prepare("INSERT INTO posts (name,group_name,sort_order) VALUES (?,?,?)").bind("Sala de Operações","COMANDO E OPERAÇÕES",1),env.DB.prepare("INSERT INTO posts (name,group_name,sort_order) VALUES (?,?,?)").bind("Praça da Juventude","PRAÇAS E PARQUES",20)]);
 const vehicleCount=await env.DB.prepare("SELECT COUNT(*) total FROM vehicles").first<{total:number}>();
 if(!vehicleCount?.total) await env.DB.batch([env.DB.prepare("INSERT INTO vehicles (prefix,type,zone) VALUES (?,?,?)").bind("VTR 1337","sedan","Zona B3 Dia"),env.DB.prepare("INSERT INTO vehicles (prefix,type,zone) VALUES (?,?,?)").bind("VTR 1302","pickup","Lomba Grande")]);
 await env.DB.prepare("INSERT OR IGNORE INTO schedules (date,status) VALUES (?,'draft')").bind(date).run();
 const schedule=await env.DB.prepare("SELECT id FROM schedules WHERE date=?").bind(date).first<{id:number}>(); if(!schedule)return;
 const assignmentCount=await env.DB.prepare("SELECT COUNT(*) total FROM assignments WHERE schedule_id=?").bind(schedule.id).first<{total:number}>(); if(assignmentCount?.total)return;
 const guards=(await env.DB.prepare("SELECT id FROM guards ORDER BY id LIMIT 4").all<{id:number}>()).results; const posts=(await env.DB.prepare("SELECT id FROM posts ORDER BY sort_order LIMIT 2").all<{id:number}>()).results; const vehicles=(await env.DB.prepare("SELECT id FROM vehicles ORDER BY id LIMIT 2").all<{id:number}>()).results;
 const times:Record<string,[string,string]>={"2":["07:00","13:00"],"3":["13:00","19:00"],"4":["19:00","01:00"],"1":["01:00","07:00"]};const commands=[];const nextDate=new Date(`${date}T12:00:00Z`);nextDate.setUTCDate(nextDate.getUTCDate()+1);const tomorrow=nextDate.toISOString().slice(0,10);
 for(const [index,shift] of shifts.entries()){const [start,end]=times[shift],endDate=shift==="4"?tomorrow:date;if(posts[0]&&guards[index%guards.length])commands.push(env.DB.prepare("INSERT INTO assignments (schedule_id,guard_id,post_id,shift,role,starts_at,ends_at,status) VALUES (?,?,?,?,?,?,?,'normal')").bind(schedule.id,guards[index%guards.length].id,posts[0].id,shift,"guard",`${date}T${start}`,`${endDate}T${end}`));if(vehicles[0]&&index<3){for(let role=0;role<2;role++)commands.push(env.DB.prepare("INSERT INTO assignments (schedule_id,guard_id,vehicle_id,shift,role,starts_at,ends_at,status) VALUES (?,?,?,?,?,?,?,'normal')").bind(schedule.id,guards[(index+role)%guards.length].id,vehicles[0].id,shift,role===0?"driver":"patrol",`${date}T${start}`,`${endDate}T${end}`))}}
 if(commands.length)await env.DB.batch(commands);
}
export async function GET(request:Request){if(!permitted(request))return Response.json({error:"Não autorizado"},{status:401});const date=new URL(request.url).searchParams.get("date")||"2026-08-12";await ensureBase(date);const schedule=await env.DB.prepare("SELECT * FROM schedules WHERE date=?").bind(date).first<Record<string,unknown>>();const [guards,posts,vehicles,assignments,movements]=await Promise.all([env.DB.prepare("SELECT id,name FROM guards WHERE active=1 ORDER BY name").all(),env.DB.prepare("SELECT id,name,group_name FROM posts WHERE active=1 ORDER BY sort_order,name").all(),env.DB.prepare("SELECT id,prefix,type,zone FROM vehicles WHERE active=1 ORDER BY prefix").all(),env.DB.prepare("SELECT a.*,g.name guard_name FROM assignments a JOIN guards g ON g.id=a.guard_id WHERE a.schedule_id=? ORDER BY a.shift,a.role,g.name").bind(schedule?.id).all(),env.DB.prepare("SELECT m.*,g.name guard_name FROM movements m JOIN guards g ON g.id=m.guard_id WHERE m.status='approved' AND m.starts_at<? AND m.ends_at>?").bind(`${date}T23:59`,`${date}T00:00`).all()]);const blocked=new Set(movements.results.map(m=>Number(m.guard_id)));const active=assignments.results.filter(a=>!blocked.has(Number(a.guard_id)));return Response.json({date,schedule,guards:guards.results,posts:posts.results,vehicles:vehicles.results,assignments:active,removed:assignments.results.filter(a=>blocked.has(Number(a.guard_id))),movements:movements.results})}
export async function POST(request:Request){if(!permitted(request))return Response.json({error:"Não autorizado"},{status:401});const b=await request.json() as Record<string,string|number|null>;if(b.action==="delete"){await env.DB.prepare("DELETE FROM assignments WHERE id=?").bind(b.id).run();return Response.json({ok:true})}const id=Number(b.id||0),guardId=Number(b.guardId),scheduleId=Number(b.scheduleId),start=String(b.startsAt),end=String(b.endsAt);const conflict=await env.DB.prepare("SELECT id FROM assignments WHERE schedule_id=? AND guard_id=? AND id!=? AND starts_at<? AND ends_at>? LIMIT 1").bind(scheduleId,guardId,id,end,start).first();if(conflict)return Response.json({error:"Conflito: este GM já está escalado nesse horário."},{status:409});const movement=await env.DB.prepare("SELECT type FROM movements WHERE guard_id=? AND status='approved' AND starts_at<? AND ends_at>? LIMIT 1").bind(guardId,end,start).first<{type:string}>();if(movement)return Response.json({error:`GM indisponível por ${movement.type}.`},{status:409});if(id)await env.DB.prepare("UPDATE assignments SET guard_id=?,post_id=?,vehicle_id=?,shift=?,role=?,starts_at=?,ends_at=?,status=?,request_ref=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(guardId,b.postId||null,b.vehicleId||null,b.shift,b.role,start,end,b.status,b.requestRef||null,id).run();else await env.DB.prepare("INSERT INTO assignments (schedule_id,guard_id,post_id,vehicle_id,shift,role,starts_at,ends_at,status,request_ref) VALUES (?,?,?,?,?,?,?,?,?,?)").bind(scheduleId,guardId,b.postId||null,b.vehicleId||null,b.shift,b.role,start,end,b.status,b.requestRef||null).run();return Response.json({ok:true})}
